package BusquedaLinealYBinaria;

public class Vocabulario {
    //"VALERIA DANAE AGUAYO MIRANDA"
    public static String[] listaOrdenada = {
            "accommodate", "active", "administer", "advertising", "age", "airline",
            "alone", "american", "animate", "apartment", "apprentice", "argument",
            "arthritis", "assessment", "athlete", "audit", "award", "bald", "baseball",
            "beast", "believe", "betray", "biology", "blend", "bone", "boyfriend", "brew",
            "buck", "busy", "camouflage", "captive", "cash", "celebration", "chairman",
            "chart", "chief", "chunk", "class", "closely", "coffin", "columnist", "common",
            "competent", "compress", "condensed", "connect", "constantly", "contemporary",
            "convenient", "copper", "couch", "cover", "creek", "cruel", "current", "dare",
            "debt", "deer", "delete", "depend", "designate", "devastate", "die", "dine",
            "disapprove", "dishonest", "distract", "doctor", "dozen", "driveway", "dye",
            "economic", "egg", "elevate", "emphasis", "engage", "enthusiastic", "equipment",
            "estimate", "everybody", "excellent", "existing", "explore", "extremely", "fair",
            "farmer", "feeble", "fiery", "finger", "flaw", "flush", "forefinger", "foster",
            "freight", "fuel", "gain", "gender", "get", "gloom", "gradual", "graze",
            "growing", "habitual", "hardy", "heal", "help", "highway", "home", "hospitable",
            "humanitarian", "i", "image", "implication", "incline", "indirect", "informative",
            "innocent", "institution", "interaction", "into", "involve", "its", "joke", "kettle",
            "knit", "lap", "layer", "legacy", "library", "limitation", "loaf", "loss", "lyric",
            "maker", "manuscript", "mash", "meaning", "memorable", "meter", "mine", "missile",
            "molecule", "mortal", "much", "mystery", "navy", "nerve", "nobody", "nourish",
            "obey", "occupy", "old", "opponent", "organize", "outlaw", "overnight", "painting",
            "paralysis", "passage", "payment", "pepper", "person", "phase", "pierce",
            "planning", "plumbing", "politician", "position", "powerful", "pregnancy",
            "pretend", "prior", "profession", "properly", "provide", "pudding", "qualify",
            "radiate", "rare", "realize", "reconcile", "reform", "regulation", "reluctance",
            "repeat", "rescue", "respirator", "retrieve", "ridiculous", "rock", "rubbish",
            "salad", "saucer", "scholarship", "search", "seizure", "sergeant", "shadow",
            "shield", "shoulder", "significance", "single", "sky", "small", "soccer",
            "somebody", "soup", "spear", "spirit", "stable", "statement", "stick",
            "straight", "strict", "stupid", "suck", "supervise", "surrender", "swift",
            "tail", "teach", "temperate", "terrestrial", "their", "thing", "throw", "today",
            "torture", "traditional", "trash", "triumph", "turn", "uncle", "unity", "upright",
            "vacation", "vegetarian", "victory", "visit", "wage", "watch", "week", "where",
            "wild", "without", "worse", "yellow"
    };
    public static String[] listaDesordenada = {
            "sufficient", "accordingly", "ancestor", "appreciate", "commit", "testimony",
            "literally", "bear", "ditch", "frequency", "sleep", "barren", "player", "hole",
            "comment", "unfortunate", "couch", "majestic", "dialogue", "current", "finance",
            "copy", "carbohydrate", "mercy", "size", "wave", "income", "living", "obvious",
            "intent", "camera", "movement", "refine", "town", "team", "heat", "sophisticated",
            "drive", "within", "founder", "hallmark", "substantial", "vulnerable",
            "strategic", "pot", "oblivious", "worth", "council", "manage", "end",
            "undergraduate", "quit", "grandmother", "craft", "stool", "primitive", "through",
            "feel", "opinion", "throw", "dangerous", "probably", "determine", "awkward",
            "guide", "gun", "ceramic", "royal", "wander", "concentration", "laundry", "legal",
            "quiver", "twig", "dedicate", "producer", "foundation", "disgrace", "tough",
            "reasonable", "meantime", "weave", "old", "stable", "tax", "brook", "dual",
            "leadership", "lost", "wipe", "startle", "contact", "lawn", "restate",
            "overnight", "condensed", "technique", "gay", "comfort", "jolly", "false",
            "meteor", "single", "alarm", "psychic", "each", "participant", "proclaim",
            "cot", "name", "nectarine", "deeply", "jewel", "hazard", "lean", "mexican",
            "ordinary", "nice", "pocket", "punishment", "song", "ready", "revenue",
            "biosphere", "commute", "northern", "prescription", "mammal", "solve",
            "letter", "terrestrial", "loose", "designate", "corpse", "dna", "benefit",
            "sock", "condemn", "input", "workout", "paste", "habit", "civic", "invalid",
            "application", "anybody", "tomb", "feedback", "escape", "care", "accurate",
            "bath", "soft", "full", "extract", "infection", "acquisition", "clothes",
            "attach", "frustration", "photo", "usually", "executive", "expectation",
            "wish", "absolutely", "radioactive", "crack", "satisfaction", "drawback",
            "senate", "resolve", "tedious", "hop", "crescent", "lime", "orange", "survey",
            "dignity", "deception", "situate", "medical", "excel", "maximize", "underground",
            "raincoat", "customer", "fragment", "secrecy", "consumption", "psychology",
            "expense", "true", "principle", "nucleus", "situation", "neutral", "scream",
            "damage", "deficit", "assess", "pierce", "invest", "improvement", "alliance",
            "reckless", "withdraw", "commission", "rugged", "able", "attorney", "sentence",
            "reef", "another", "horse", "instead", "poverty", "frigid", "package", "tip",
            "hurricane", "garlic", "bond", "apart", "kid", "clumsy", "cramp", "victor",
            "rest", "smile", "also", "treatment", "hypothesis", "foot", "mimic", "table",
            "way", "cease", "dew", "movie", "mass", "typically", "establishment", "cargo",
            "arena", "accompany", "pregnancy"
    };
}
